### ISSUE TITLE
Adding Friendica instance fails

### ISSUE THREAD

**Issue by Alkarex** [jaywink/the-federation.info#118] opened 2017-10-31 19:39 UTC
Hello,
I have tried to add my Friendica instance https://f.a80.fr to https://the-federation.info/friendica a couple of times in the past few days and it is still not listed.
Any idea of what is wrong?

**Comment by jaywink** [comment] 2017-10-31 20:42
Hi @Alkarex 

Does your instance have the Diaspora protocol activated? The-federation.info logs say your node is giving 404 for the routes tried.

the-federation.info registration requires support for the Diaspora protocol, unfortunately at the moment, until we make the site show information about multiple protocols.

**Comment by Alkarex** [comment] 2017-11-01 08:32
Thanks for the quick response, @jaywink .
Yes, my Friendica instance supports Diaspora* in both directions. See e.g. https://f.a80.fr/viewcontacts/alkarex

This is what I see from my side:

```
f.a80.fr:443 46.4.94.47 - - [01/Nov/2017:09:21:12 +0100] "GET /.well-known/x-nodeinfo2 HTTP/1.1" 404 3301 "-" "-"
f.a80.fr:443 46.4.94.47 - - [01/Nov/2017:09:21:12 +0100] "GET /.well-known/nodeinfo HTTP/1.1" 200 3364 "-" "-"
f.a80.fr:443 46.4.94.47 - - [01/Nov/2017:09:21:12 +0100] "GET /nodeinfo/1.0 HTTP/1.1" 404 3301 "-" "-"
f.a80.fr:443 46.4.94.47 - - [01/Nov/2017:09:21:12 +0100] "GET /statistics.json HTTP/1.1" 404 3301 "-" "-"
```

@annando Any idea of what to do from Friendica side? I am running the latest /develop branch, in single-user mode.

![image](https://user-images.githubusercontent.com/1008324/32266359-676c3616-bee7-11e7-8aee-6e1df4b64bd1.png)

**Comment by jaywink** [comment] 2017-11-01 09:18
@annando I hope Friendica didn't just drop NodeInfo 1.0 support? NodeInfo is versioned (which is a mistake by the authors but they wont acknowledge that), the old versions can't just be dropped when a new version comes out..

**Comment by jaywink** [comment] 2017-11-01 10:12
Hmm actually the JSON for nodeinfo endpoints does list 1.0, but not 2.0:

```
{
    "links": [
        {
            "rel": "http://nodeinfo.diaspora.software/ns/schema/1.0",
            "href": "https://f.a80.fr/nodeinfo/1.0"
        }
    ]
}
```

Note, the-federation.info does not support NodeInfo 2.0 version yet.

**Comment by annando** [comment] 2017-11-01 13:56
It should work without any problem like you can see on my server pirati.ca.

**Comment by jaywink** [comment] 2017-11-01 14:01
@Alkarex so basically your https://f.a80.fr/nodeinfo/1.0 document is 404 even though it shouldn't be. This is either a Friendica or server configuration issue. Either way, it doesn't look like an issue in this repository. You said you use a development version, maybe it's a regression?

Either way, I'll close this here. Hope the problem is sorted for you soon 👍

**Closed by jaywink** 2017-11-01 14:01 UTC
Labels: upstream

**Comment by annando** [comment] 2017-11-01 14:32
@Alkarex please open up a Friendica issue. Then we can have a look at it.
